name: ci

on:
  pull_request:
  push:
    branches:
      [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.25.1"

    - name: Run go tests
      run: go test --cover ./...

    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run gosec
      run: $(go env GOPATH)/bin/gosec ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.25.1"

    - name: Check formatting
      run: test -z $(go fmt ./...)

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: run staticcheck
      run: $(go env GOPATH)/bin/staticcheck ./...


